"""empty message

Revision ID: 5c27b6504623
Revises: a80cd22104ad
Create Date: 2021-03-30 23:56:42.176763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c27b6504623'
down_revision = 'a80cd22104ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('DNI_doctor_hospital', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hospital', 'doctor', ['DNI_doctor_hospital'], ['DNI_doctor'])
    op.drop_column('hospital', 'birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('birth', mysql.VARCHAR(length=250), nullable=False))
    op.drop_constraint(None, 'hospital', type_='foreignkey')
    op.drop_column('hospital', 'DNI_doctor_hospital')
    # ### end Alembic commands ###
