"""empty message

Revision ID: 71afd56fff75
Revises: a490dbe69514
Create Date: 2021-03-30 21:16:02.693169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71afd56fff75'
down_revision = 'a490dbe69514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('DNI_doctor', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('Especialidad', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('DNI_doctor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor')
    # ### end Alembic commands ###
