"""empty message

Revision ID: b605ff6161a2
Revises: 71afd56fff75
Create Date: 2021-03-30 23:50:08.761157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b605ff6161a2'
down_revision = '71afd56fff75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospital', 'Hora',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospital', 'Hora',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
